### ISSUE TITLE
Create android emulator image for browser tests

### ISSUE THREAD

**Issue by AleksanderPopov** [aerokube/selenoid-images#10]
Guys, can you please create image with android emulator for selenoid, it will be very helpful for mobile testing

**Comment by elgalu** [comment]
My colleague @butomo1989 built a x86 based https://github.com/butomo1989/docker-android dockerized emulator. Not slow as the arm one. It's 4.52GB though, not sure if the image size can be optimized and how much but mobile testers might be ready to accept the one-time download time.

**Comment by vania-pooh** [comment]
Added Dockerfile for Android images [here](https://github.com/aerokube/selenoid-images/tree/master/selenium/android). Appium starts on its default port 4723. Image size should be approximately 3.8 Gb. I assume that this is only to demonstrate the main ideas - in order to use Android you need to customize the source files and build the image yourself.
