### ISSUE TITLE
[Feature] Changelog

### ISSUE THREAD

**Issue by conradkirschner** [aerokube/selenoid-images#275]
Hi, 

I see a lot changes in this repo, but it was quite hard to look into the git log to find out what actual changed. 

A changelog would give me a better overview what is going on :)

If I overlooked it, I am sorry for it.

**Comment by vania-pooh** [comment]
@conradkirschner basically we migrated from bash scripts to Golang binary doing the same logic. This wasn't yet released but new commands are already in README.md.

**Comment by conradkirschner** [comment]
I was more into the permission fixes, if you had included it and how you did it... :D (As my pull request wasn't that good) 
That's why I was digging in the git log. 

It's more a general thing for all your open repos, looking into gitlog to find out what changed is harder than read a small changelog... 

But it's up to you, if you dislike changelogs for any reason (too time consuming) just close this request and I will stay with the gitlog 

More Help if you like Changelogs or not:

https://keepachangelog.com/en/1.0.0/

**Comment by vania-pooh** [comment]
@conradkirschner I think we could start adding changelog to Github releases like we do e.g. for [Selenoid](https://github.com/aerokube/selenoid/releases).

**Comment by Expoverse** [comment]
It's possible to auto generate a change log from git tags and commit history. So instead of starting MORE work, let most of it be automated. Which provides a clearer communication what what exactly happened in the version being released. h[ttps://github.com/CookPete/auto-changelog](url) is a simple tool to do this to save time on rewriting every change into a change log.  


#### Below is an exact copy and paste of the change log generated by this tool
You can click this link to view it in a separate tab. [https://github.com/CookPete/auto-changelog/blob/master/CHANGELOG.md](url)

### Changelog

All notable changes to this project will be documented in this file. Dates are displayed in UTC.

Generated by [`auto-changelog`](https://github.com/CookPete/auto-changelog).

#### [v2.2.0](https://github.com/CookPete/auto-changelog/compare/v2.1.0...v2.2.0)

> 3 July 2020

- add --prepend option as altenative to prepend-token [`#172`](https://github.com/CookPete/auto-changelog/pull/172)
- Fix bug when no existing tags [`#170`](https://github.com/CookPete/auto-changelog/issues/170)

#### [v2.1.0](https://github.com/CookPete/auto-changelog/compare/v2.0.0...v2.1.0)

> 14 June 2020

- Add --hide-credit option [`#166`](https://github.com/CookPete/auto-changelog/issues/166)
- Add --unreleased-only option [`#165`](https://github.com/CookPete/auto-changelog/issues/165)
- Fix --starting-version [`#164`](https://github.com/CookPete/auto-changelog/issues/164)
- Add ability to prepend to an existing changelog [`#156`](https://github.com/CookPete/auto-changelog/issues/156)
- Use tag date rather than first commit date [`#162`](https://github.com/CookPete/auto-changelog/issues/162)
- Add CONTRIBUTING.md [`#141`](https://github.com/CookPete/auto-changelog/issues/141)
- Add merge and fix support to commit-list helper [`#146`](https://github.com/CookPete/auto-changelog/issues/146)

### [v2.0.0](https://github.com/CookPete/auto-changelog/compare/v1.16.4...v2.0.0)

> 10 April 2020

- Refactor codebase [`#144`](https://github.com/CookPete/auto-changelog/pull/144)
- **Breaking change:** Remove the need for core-js and building with babel [`2383380`](https://github.com/CookPete/auto-changelog/commit/23833803c4d4652a139a43bb5b6767adc604988b)
- **Breaking change:** Refactor git data fetching logic [`09325ac`](https://github.com/CookPete/auto-changelog/commit/09325aca59fff94aae0b5f457311fca1956276ac)
- Improve progress output [`a2ba4ac`](https://github.com/CookPete/auto-changelog/commit/a2ba4ac01d6dff2b2b08ac6262ffc0bbd4afdb83)

#### [v1.16.4](https://github.com/CookPete/auto-changelog/compare/v1.16.3...v1.16.4)

> 2 April 2020

- Pin semver to v6 [`#160`](https://github.com/CookPete/auto-changelog/issues/160)
- Add node 12 to travis builds [`ac77a53`](https://github.com/CookPete/auto-changelog/commit/ac77a537e9db115317ca0a53c68e11b5968763d4)
- Remove node 8 from travis builds [`e7d557d`](https://github.com/CookPete/auto-changelog/commit/e7d557d02d61c955194da95cee6cc3390b529791)

#### [v1.16.3](https://github.com/CookPete/auto-changelog/compare/v1.16.2...v1.16.3)

> 25 March 2020

- Bump handlebars from 4.1.2 to 4.3.0 [`#147`](https://github.com/CookPete/auto-changelog/pull/147)
- Bump packages [`1ced7a8`](https://github.com/CookPete/auto-changelog/commit/1ced7a8017319643be3b41847fe14c3195b88256)
- Add FUNDING.yml [`107445f`](https://github.com/CookPete/auto-changelog/commit/107445f3739cecb8061422c000be522d6e250867)

#### [v1.16.2](https://github.com/CookPete/auto-changelog/compare/v1.16.1...v1.16.2)

> 29 October 2019

- fix parsing of --issue-url and -i options [`#138`](https://github.com/CookPete/auto-changelog/pull/138)
- Use noEscape option rather than triple brackets everywhere [`#131`](https://github.com/CookPete/auto-changelog/issues/131) [`#133`](https://github.com/CookPete/auto-changelog/pull/133)

#### [v1.16.1](https://github.com/CookPete/auto-changelog/compare/v1.16.0...v1.16.1)

> 4 September 2019

- Encode &lt; and &gt; in commit messages [`#129`](https://github.com/CookPete/auto-changelog/issues/129)
- Update test data generation [`c2c9bd8`](https://github.com/CookPete/auto-changelog/commit/c2c9bd82ab1857009b8e4e5bcb514312fdd43975)
- Refactor release parsing [`b1ab27e`](https://github.com/CookPete/auto-changelog/commit/b1ab27e258c4b2b4f0f2bea2f0fe8d9a2f66926e)
- Add HTML characters to test data [`b4eb7d7`](https://github.com/CookPete/auto-changelog/commit/b4eb7d7bdd1187a13b89db20f56a6acde0b1b8e5)

#### [v1.16.0](https://github.com/CookPete/auto-changelog/compare/v1.15.0...v1.16.0)

> 31 August 2019

- Add --commit-url, --merge-url and --compare-url options [`#93`](https://github.com/CookPete/auto-changelog/issues/93)
- Bump packages [`84a1bda`](https://github.com/CookPete/auto-changelog/commit/84a1bdadc21926b16df39886c2f2d799a92bd64f)
- Update readme [`a04c0ff`](https://github.com/CookPete/auto-changelog/commit/a04c0ff7a894aaf55627ba6decb8f7e07aea7479)
- Lint fixes [`7d3c25a`](https://github.com/CookPete/auto-changelog/commit/7d3c25afad1f49da8bb38df915f2430514da2d53)

#### [v1.15.0](https://github.com/CookPete/auto-changelog/compare/v1.14.1...v1.15.0)

> 13 August 2019

- Add --config option [`#127`](https://github.com/CookPete/auto-changelog/issues/127)
- Infer semver versions from numeric tags [`#126`](https://github.com/CookPete/auto-changelog/issues/126)

#### [v1.14.1](https://github.com/CookPete/auto-changelog/compare/v1.14.0...v1.14.1)

> 8 July 2019

- Add regenerator-runtime dependency [`#125`](https://github.com/CookPete/auto-changelog/issues/125)

#### [v1.14.0](https://github.com/CookPete/auto-changelog/compare/v1.13.0...v1.14.0)

> 7 July 2019

- Update babel/rimraf/nyc [`#122`](https://github.com/CookPete/auto-changelog/pull/122)
- HTTPS links to external sites [`#120`](https://github.com/CookPete/auto-changelog/pull/120)
- Add support for alternate date sorting [`#113`](https://github.com/CookPete/auto-changelog/pull/113)
- fix for handlebars-setup arg [`#110`](https://github.com/CookPete/auto-changelog/pull/110)
- Add --append-git-log option [`#118`](https://github.com/CookPete/auto-changelog/pull/118) [`#117`](https://github.com/CookPete/auto-changelog/issues/117)
- Update test data [`bb3a347`](https://github.com/CookPete/auto-changelog/commit/bb3a3475bc0c5d394727cec62486df0f5dcff9e1)
- Add commit object to merge data [`2a8de35`](https://github.com/CookPete/auto-changelog/commit/2a8de35e56e7cf43056c0f1850976699957664e1)
- Fix commander argument syntax [`01739fe`](https://github.com/CookPete/auto-changelog/commit/01739fea2accc264bde29be99b53c827f44ba1e9)

#### [v1.13.0](https://github.com/CookPete/auto-changelog/compare/v1.12.1...v1.13.0)

> 16 April 2019

- Support partial semver tag sorting [`#94`](https://github.com/CookPete/auto-changelog/issues/94)
- Update --package option to accept file path [`#106`](https://github.com/CookPete/auto-changelog/issues/106)
- Tidy up getOptions [`0168216`](https://github.com/CookPete/auto-changelog/commit/0168216be9976d918ca4f64168d7c8db53cc9cb8)
- Tidy up readJson util [`36bfd9e`](https://github.com/CookPete/auto-changelog/commit/36bfd9e89f3a9f9d40aa54765141e1be70d8ff06)
- Space out error logs [`2bc35ce`](https://github.com/CookPete/auto-changelog/commit/2bc35ce4e57f68990a69f2c2846610015330a50f)

#### [v1.12.1](https://github.com/CookPete/auto-changelog/compare/v1.12.0...v1.12.1)

> 11 April 2019

- Change behaviour of ignoreCommitPattern to see tags on ignored commits [`#102`](https://github.com/CookPete/auto-changelog/pull/102)
- Bump packages [`b371147`](https://github.com/CookPete/auto-changelog/commit/b371147dea0b483663a040b69e4193944b951b51)
- Remove greenkeeper [`b0841c8`](https://github.com/CookPete/auto-changelog/commit/b0841c8a6af737ea0ca3c00a98015b10fdd0821a)

#### [v1.12.0](https://github.com/CookPete/auto-changelog/compare/v1.11.0...v1.12.0)

> 18 March 2019

- Add main entry to package.json [`#87`](https://github.com/CookPete/auto-changelog/pull/87)
- Update mocha to the latest version 🚀 [`#88`](https://github.com/CookPete/auto-changelog/pull/88)
- Add --merge-pattern option [`#86`](https://github.com/CookPete/auto-changelog/pull/86)
- yarn upgrade [`#91`](https://github.com/CookPete/auto-changelog/pull/91)
- Add --handlebars-setup option [`#96`](https://github.com/CookPete/auto-changelog/issues/96) [`#89`](https://github.com/CookPete/auto-changelog/issues/89) [`#90`](https://github.com/CookPete/auto-changelog/pull/90)
- Add --sort-commits option [`#95`](https://github.com/CookPete/auto-changelog/issues/95) [`#97`](https://github.com/CookPete/auto-changelog/pull/97)

#### [v1.11.0](https://github.com/CookPete/auto-changelog/compare/v1.10.3...v1.11.0)

> 14 January 2019

- Add --stdout option [`#83`](https://github.com/CookPete/auto-changelog/issues/83)
- Fix sortReleases for non-semver tags [`#81`](https://github.com/CookPete/auto-changelog/issues/81)
- Add backtick characters to test data [`ab73c8a`](https://github.com/CookPete/auto-changelog/commit/ab73c8a265b93992fa61999dde8962e61ef60c64)

#### [v1.10.3](https://github.com/CookPete/auto-changelog/compare/v1.10.2...v1.10.3)

> 4 January 2019

- Clarify includeBranch config array in readme [`#75`](https://github.com/CookPete/auto-changelog/issues/75)
- Remove package-lock.json from repo [`512205b`](https://github.com/CookPete/auto-changelog/commit/512205b1a028d3ded629c84d475a15fc2e44163c)
- Sort and slice commits for latest release [`7d7f377`](https://github.com/CookPete/auto-changelog/commit/7d7f377c17384b8b80c71ffb9bcd2900640255e3)
- Fix breaking commit sorting [`73c05a1`](https://github.com/CookPete/auto-changelog/commit/73c05a1f3218dccc9a7e9f46577c45fb1af986e3)

#### [v1.10.2](https://github.com/CookPete/auto-changelog/compare/v1.10.1...v1.10.2)

> 18 November 2018

- Upgrade all packages [`#59`](https://github.com/CookPete/auto-changelog/pull/59)
- Remove package-lock.json [`791a261`](https://github.com/CookPete/auto-changelog/commit/791a2617361657630e389b09e193ca57c237623d)

#### [v1.10.1](https://github.com/CookPete/auto-changelog/compare/v1.10.0...v1.10.1)

> 13 November 2018

- Use readline for log util [`#73`](https://github.com/CookPete/auto-changelog/issues/73) [`#74`](https://github.com/CookPete/auto-changelog/issues/74)

#### [v1.10.0](https://github.com/CookPete/auto-changelog/compare/v1.9.0...v1.10.0)

> 10 November 2018

- Update tests [`644f5d8`](https://github.com/CookPete/auto-changelog/commit/644f5d8a79042431c0a89f99866034ac124cce56)
- Add better progress logging [`64ebb30`](https://github.com/CookPete/auto-changelog/commit/64ebb30b8e979afa028ec2b147405b3cbf854e36)
- Add --backfill-limit option [`5240b1e`](https://github.com/CookPete/auto-changelog/commit/5240b1e5298a2a0bef405100ab03636b491306c0)

#### [v1.9.0](https://github.com/CookPete/auto-changelog/compare/v1.8.1...v1.9.0)

> 8 November 2018

- Add support for azure devops and visualstudio.com [`#72`](https://github.com/CookPete/auto-changelog/pull/72)
- Bump packages [`#56`](https://github.com/CookPete/auto-changelog/pull/56) [`#60`](https://github.com/CookPete/auto-changelog/pull/60) [`#61`](https://github.com/CookPete/auto-changelog/pull/61)
- Add --tag-pattern option [`#70`](https://github.com/CookPete/auto-changelog/pull/70)
- Add support for .auto-changelog config [`#66`](https://github.com/CookPete/auto-changelog/pull/66)
- Add --release-summary option [`#69`](https://github.com/CookPete/auto-changelog/issues/69)
- Add tests for `.auto-changelog` feature [`17b0926`](https://github.com/CookPete/auto-changelog/commit/17b09269fa5603e0be7f5ffe5ce67996f7cf4176)
- Add tests for sortReleases [`9d80b9d`](https://github.com/CookPete/auto-changelog/commit/9d80b9d8a7dfcb5f0db37dad1fa8757e3124c564)
- Fix quote style [`5c18eda`](https://github.com/CookPete/auto-changelog/commit/5c18edaebff560e3e982a8d58ee7473f24b6be24)

#### [v1.8.1](https://github.com/CookPete/auto-changelog/compare/v1.8.0...v1.8.1)

> 8 October 2018

- Fix Bitbucket compare links. [`#65`](https://github.com/CookPete/auto-changelog/pull/65)
- Update markdownlint-cli to the latest version 🚀 [`#54`](https://github.com/CookPete/auto-changelog/pull/54)
- Update markdownlint-cli to the latest version 🚀 [`#51`](https://github.com/CookPete/auto-changelog/pull/51)
- Add author to fixes and merges [`#58`](https://github.com/CookPete/auto-changelog/issues/58)
- Remove unsupported node versions from travis builds [`df63917`](https://github.com/CookPete/auto-changelog/commit/df63917391f3b30ceaa13a774b05889e659e4dd4)
- Add timeout to URL fetching test [`d635a06`](https://github.com/CookPete/auto-changelog/commit/d635a06cf9e544fd4b11a9f6eed0fbdc597d41ea)
- Add node 6.0 to travis builds [`088077e`](https://github.com/CookPete/auto-changelog/commit/088077e51fe581d41dfeb56b009845be9d9e3c65)

#### [v1.8.0](https://github.com/CookPete/auto-changelog/compare/v1.7.2...v1.8.0)

> 23 July 2018

- Add support for external templates [`#49`](https://github.com/CookPete/auto-changelog/issues/49) [`#50`](https://github.com/CookPete/auto-changelog/pull/50)
- Bump nyc [`#46`](https://github.com/CookPete/auto-changelog/pull/46)
- Add README.md to lint checks [`5aab29f`](https://github.com/CookPete/auto-changelog/commit/5aab29f18d4187fa2480cd7754eba8e579ea0534)
- Tweak readme headings [`9f08899`](https://github.com/CookPete/auto-changelog/commit/9f08899466ccc515609456192e15d60c60db411b)
- Remove git from engines [`bac0248`](https://github.com/CookPete/auto-changelog/commit/bac024828c93587ea4603865e5946382f9e88070)

#### [v1.7.2](https://github.com/CookPete/auto-changelog/compare/v1.7.1...v1.7.2)

> 28 June 2018

- Fix unreleased section sorting [`#48`](https://github.com/CookPete/auto-changelog/issues/48)
- Add markdown linting [`#47`](https://github.com/CookPete/auto-changelog/issues/47)
- Fix changelog spacing [`5e8ffe5`](https://github.com/CookPete/auto-changelog/commit/5e8ffe564b2752f4f1828d64174cc784f6168fdf)
- Use %B for supported git versions [`1b9c3d7`](https://github.com/CookPete/auto-changelog/commit/1b9c3d71732244b6a2c265dae9aae879bd5f33b2)
- Enable partial line coverage with codecov [`e0d24de`](https://github.com/CookPete/auto-changelog/commit/e0d24debb40967014aea1bcc1738bbc1d0279ba2)

#### [v1.7.1](https://github.com/CookPete/auto-changelog/compare/v1.7.0...v1.7.1)

> 31 May 2018

- Fix releases sorting when unreleased enabled [`#45`](https://github.com/CookPete/auto-changelog/pull/45)
- Use async fs utils instead of fs-extra [`#42`](https://github.com/CookPete/auto-changelog/pull/42)
- Update git log format to support earlier git versions [`#43`](https://github.com/CookPete/auto-changelog/issues/43)

#### [v1.7.0](https://github.com/CookPete/auto-changelog/compare/v1.6.0...v1.7.0)

> 23 May 2018

- Add replaceText package option [`77d73ee`](https://github.com/CookPete/auto-changelog/commit/77d73ee4a44d5d207ba0982bf1e27812739d542a)

#### [v1.6.0](https://github.com/CookPete/auto-changelog/compare/v1.5.0...v1.6.0)

> 17 May 2018

- Add --breaking-pattern option [`#41`](https://github.com/CookPete/auto-changelog/issues/41)
- Add --include-branch option [`#38`](https://github.com/CookPete/auto-changelog/issues/38)
- Fix duplicate test data commit hashes [`7f448ce`](https://github.com/CookPete/auto-changelog/commit/7f448ce7154e7da4d677aa4c96a2721499436edb)

#### [v1.5.0](https://github.com/CookPete/auto-changelog/compare/v1.4.6...v1.5.0)

> 16 May 2018

- Feat: match template helper [`#40`](https://github.com/CookPete/auto-changelog/pull/40)
- Add commit-list template helper [`#36`](https://github.com/CookPete/auto-changelog/issues/36) [`#39`](https://github.com/CookPete/auto-changelog/issues/39)
- Use UTC dates by default [`#37`](https://github.com/CookPete/auto-changelog/issues/37)
- Move helper tests to separate files [`71388c2`](https://github.com/CookPete/auto-changelog/commit/71388c2dca9d9d50df540f904de5b3c0c0fea86a)
- Remove unused imports from template tests [`5ca7c61`](https://github.com/CookPete/auto-changelog/commit/5ca7c619dd9f8ca02cdcb67469025f71ab10cc2f)

#### [v1.4.6](https://github.com/CookPete/auto-changelog/compare/v1.4.5...v1.4.6)

> 15 March 2018

- Added support for old git versions [`#35`](https://github.com/CookPete/auto-changelog/pull/35)

#### [v1.4.5](https://github.com/CookPete/auto-changelog/compare/v1.4.4...v1.4.5)

> 27 February 2018

- Correctly prefix package version [`#33`](https://github.com/CookPete/auto-changelog/issues/33)

#### [v1.4.4](https://github.com/CookPete/auto-changelog/compare/v1.4.3...v1.4.4)

> 22 February 2018

- Do not show date for unreleased section [`#31`](https://github.com/CookPete/auto-changelog/issues/31)
- Fix unreleased compare URL [`24fbc63`](https://github.com/CookPete/auto-changelog/commit/24fbc63adfad6df630d496d7cf1c488d97189dfe)

#### [v1.4.3](https://github.com/CookPete/auto-changelog/compare/v1.4.2...v1.4.3)

> 21 February 2018

- Add tag prefix to compare URLs [`#30`](https://github.com/CookPete/auto-changelog/issues/30)

#### [v1.4.2](https://github.com/CookPete/auto-changelog/compare/v1.4.1...v1.4.2)

> 20 February 2018

- Support for gitlab subgroups and self-hosted instances [`#28`](https://github.com/CookPete/auto-changelog/pull/28)
- Update standard to the latest version 🚀 [`#29`](https://github.com/CookPete/auto-changelog/pull/29)

#### [v1.4.1](https://github.com/CookPete/auto-changelog/compare/v1.4.0...v1.4.1)

> 30 January 2018

- Support commits with no message [`#27`](https://github.com/CookPete/auto-changelog/issues/27)

#### [v1.4.0](https://github.com/CookPete/auto-changelog/compare/v1.3.0...v1.4.0)

> 18 January 2018

- Update mocha to the latest version 🚀 [`#26`](https://github.com/CookPete/auto-changelog/pull/26)
- Add support for generating logs without a git remote [`#23`](https://github.com/CookPete/auto-changelog/issues/23)
- Update niceDate tests to avoid timezone issues [`#24`](https://github.com/CookPete/auto-changelog/issues/24) [`#25`](https://github.com/CookPete/auto-changelog/pull/25)
- Add --tag-prefix option [`#22`](https://github.com/CookPete/auto-changelog/issues/22)
- Change use of "origin" to "remote" [`7c9c175`](https://github.com/CookPete/auto-changelog/commit/7c9c1757257be10e3beae072941d119d195becd7)
- Add --ignore-commit-pattern option [`8cbe121`](https://github.com/CookPete/auto-changelog/commit/8cbe121e857b8d99361e65fa462d035610f741c9)
- Add merge commit to test data [`4462118`](https://github.com/CookPete/auto-changelog/commit/4462118a26b5d76b276c8e1ba938f5c7d4458572)

#### [v1.3.0](https://github.com/CookPete/auto-changelog/compare/v1.2.2...v1.3.0)

> 21 December 2017

- Update fs-extra to the latest version 🚀 [`#19`](https://github.com/CookPete/auto-changelog/pull/19)
- Add --starting-commit option [`#21`](https://github.com/CookPete/auto-changelog/issues/21)
- Add --issue-pattern option [`#18`](https://github.com/CookPete/auto-changelog/issues/18)
- Add --latest-version option [`#17`](https://github.com/CookPete/auto-changelog/issues/17)
- Override package options with command line options [`20e3962`](https://github.com/CookPete/auto-changelog/commit/20e3962175c8168ec5494d1527b16e996e113777)
- Update tests [`2a74da4`](https://github.com/CookPete/auto-changelog/commit/2a74da474c3366f740cedb1c31a9c2539a1c9261)

#### [v1.2.2](https://github.com/CookPete/auto-changelog/compare/v1.2.1...v1.2.2)

> 5 December 2017

- Fix error when using --unreleased flag [`#16`](https://github.com/CookPete/auto-changelog/issues/16)

#### [v1.2.1](https://github.com/CookPete/auto-changelog/compare/v1.2.0...v1.2.1)

> 4 December 2017

- Filter out merge commits [`#14`](https://github.com/CookPete/auto-changelog/pull/14)
- Add commit to test data to trigger sorting [`9aa7ed4`](https://github.com/CookPete/auto-changelog/commit/9aa7ed493138286134a18a018d77ac7f5a11fc43)
- Add tests [`02613a3`](https://github.com/CookPete/auto-changelog/commit/02613a36e1071fb64a9d1251e4dae6d683a5b845)
- Add commit with matching PR message to test data [`e9a43b2`](https://github.com/CookPete/auto-changelog/commit/e9a43b2bf50449fc0d84465308e6008cc1597bb3)

#### [v1.2.0](https://github.com/CookPete/auto-changelog/compare/v1.1.0...v1.2.0)

> 1 December 2017

- Add issue-url option to override issue URLs [`#13`](https://github.com/CookPete/auto-changelog/issues/13)
- Add major release to test data [`e14f753`](https://github.com/CookPete/auto-changelog/commit/e14f753fc39fb94f3a3ffc3ab9a41015a9b97f2f)
- Update readme [`aaa69d0`](https://github.com/CookPete/auto-changelog/commit/aaa69d096cbf289e5fa086bbbd04e3ec27bcb7a4)
- Slightly larger heading for major releases [`d618f01`](https://github.com/CookPete/auto-changelog/commit/d618f019abc59da903cbafaa49ac9731e815b95a)

#### [v1.1.0](https://github.com/CookPete/auto-changelog/compare/v1.0.3...v1.1.0)

> 9 November 2017

- Support modifying commit limit with --commit-limit [`#12`](https://github.com/CookPete/auto-changelog/pull/12)
- Move test origins to separate file [`f8b98b5`](https://github.com/CookPete/auto-changelog/commit/f8b98b536612a89c0f93eb6451be90d857468eac)
- Add origin tests [`f50dced`](https://github.com/CookPete/auto-changelog/commit/f50dced289d3780726b67abfba3359c6b83c6ca7)
- Add run tests [`a6ae95e`](https://github.com/CookPete/auto-changelog/commit/a6ae95ec1045dbb76540dde63cafa4fbaa0fc030)

#### [v1.0.3](https://github.com/CookPete/auto-changelog/compare/v1.0.2...v1.0.3)

> 7 November 2017

- Fix pull request URL [`3f6daaa`](https://github.com/CookPete/auto-changelog/commit/3f6daaa35b3da08bafec0ef9229cb4b09bc1c9cb)
- Bump packages [`510c798`](https://github.com/CookPete/auto-changelog/commit/510c798fe6bb688234bb8b4eb3885055a47ee2bb)
- Fix version script [`f849dac`](https://github.com/CookPete/auto-changelog/commit/f849dac557b2c24512c553d9fccb93e1455a8c2e)

#### [v1.0.2](https://github.com/CookPete/auto-changelog/compare/v1.0.1...v1.0.2)

> 31 October 2017

- Tweak package read logic [`5ca75a2`](https://github.com/CookPete/auto-changelog/commit/5ca75a2a051a496fe7899185d486dc6447a44d7a)
- Fall back to https origin protocol [`74e29b4`](https://github.com/CookPete/auto-changelog/commit/74e29b4c40a8522a8aa33b6b66e845859dbcde1d)

#### [v1.0.1](https://github.com/CookPete/auto-changelog/compare/v1.0.0...v1.0.1)

> 27 October 2017

- Filter out commits with the same message as an existing merge [`2a420f7`](https://github.com/CookPete/auto-changelog/commit/2a420f793ac3b761291cfd5499676a80953cbee7)
- Update readme [`54fc665`](https://github.com/CookPete/auto-changelog/commit/54fc6659e9283b6d6afc95486893aa56df13111c)

### [v1.0.0](https://github.com/CookPete/auto-changelog/compare/v0.3.6...v1.0.0)

> 27 October 2017

- Update dependencies to enable Greenkeeper 🌴 [`#10`](https://github.com/CookPete/auto-changelog/pull/10)
- Refactor codebase [`dab29fb`](https://github.com/CookPete/auto-changelog/commit/dab29fb3a030ffe2799075ef46c70c734d8d2b89)
- Add greenkeeper-lockfile support [`126c6fb`](https://github.com/CookPete/auto-changelog/commit/126c6fbd054c16624ab39cbb51a2eab99bc832c6)
- Tweak readme badges [`bf73f55`](https://github.com/CookPete/auto-changelog/commit/bf73f555422ef5338455182b9649badc122bdadf)

#### [v0.3.6](https://github.com/CookPete/auto-changelog/compare/v0.3.5...v0.3.6)

> 23 October 2017

- Use origin hostname instead of host [`#9`](https://github.com/CookPete/auto-changelog/issues/9)
- Correct bitbucket compare URLs [`9d34452`](https://github.com/CookPete/auto-changelog/commit/9d344527171c158e1d56fdfde5cce870c5ba84bf)

#### [v0.3.5](https://github.com/CookPete/auto-changelog/compare/v0.3.4...v0.3.5)

> 6 October 2017

- Add babel-polyfill [`#8`](https://github.com/CookPete/auto-changelog/issues/8)

#### [v0.3.4](https://github.com/CookPete/auto-changelog/compare/v0.3.3...v0.3.4)

> 5 October 2017

- Add code coverage [`786af11`](https://github.com/CookPete/auto-changelog/commit/786af11c841fe158fbb8eb3d6a0e2c0ee8b1a93a)
- Use async/await instead of promises [`dff4653`](https://github.com/CookPete/auto-changelog/commit/dff465371252ce6ab4cd05e49d4c41fd8d3bb37a)
- Remove need for array.find polyfill [`78a1cb8`](https://github.com/CookPete/auto-changelog/commit/78a1cb8ac9327ecb0efadffed037f90191bdce5a)

#### [v0.3.3](https://github.com/CookPete/auto-changelog/compare/v0.3.2...v0.3.3)

> 24 September 2017

- Bump packages [`#7`](https://github.com/CookPete/auto-changelog/issues/7)
- Use babel-preset-env [`3eb90ce`](https://github.com/CookPete/auto-changelog/commit/3eb90ce74791fa803e3013aab12d0ff3cecc403b)
- Lint fix [`67c38dd`](https://github.com/CookPete/auto-changelog/commit/67c38ddf70b7420de0a9bae061efe858e879e0b7)

#### [v0.3.2](https://github.com/CookPete/auto-changelog/compare/v0.3.1...v0.3.2)

> 14 September 2017

- Prevent duplicate commits being listed [`#3`](https://github.com/CookPete/auto-changelog/issues/3)

#### [v0.3.1](https://github.com/CookPete/auto-changelog/compare/v0.3.0...v0.3.1)

> 9 September 2016

- Improve origin URL parsing [`#2`](https://github.com/CookPete/auto-changelog/issues/2) [`#5`](https://github.com/CookPete/auto-changelog/issues/5)
- Remove semicolons [`2ff61e2`](https://github.com/CookPete/auto-changelog/commit/2ff61e2f6b415bd24cfdf1788a3a4239138e6aa2)
- More robust log separators [`adc1dcc`](https://github.com/CookPete/auto-changelog/commit/adc1dccb744335ed1b0cb52a32f23605f92bbe97)
- Improve error handling [`96b7666`](https://github.com/CookPete/auto-changelog/commit/96b7666e50126dc515bb7bf2f9a79090ad7d8806)

#### [v0.3.0](https://github.com/CookPete/auto-changelog/compare/v0.2.2...v0.3.0)

> 11 January 2016

- Add semicolons after class properties [`07b2de5`](https://github.com/CookPete/auto-changelog/commit/07b2de5131f4354565b2ba94a5fc181a1448b5c2)
- Remove unique issue filter [`11acb7e`](https://github.com/CookPete/auto-changelog/commit/11acb7e4a9f2782a95e0932917828646103bd85a)
- Add support for minimumChangeCount in templates [`612d80b`](https://github.com/CookPete/auto-changelog/commit/612d80b02cabbc2faeddd39c57bd086661932aef)

#### [v0.2.2](https://github.com/CookPete/auto-changelog/compare/v0.2.1...v0.2.2)

> 2 January 2016

- Add a commit-only release to test data [`99927a9`](https://github.com/CookPete/auto-changelog/commit/99927a9b2126e656f70964f303a477aa4a5f811b)
- Update templating logic [`12c0624`](https://github.com/CookPete/auto-changelog/commit/12c0624e7e419a70bd5f3b403d7e0bd8f23ec617)
- More sensible formatDate [`db92947`](https://github.com/CookPete/auto-changelog/commit/db92947e6129cc20cd7777b7ed90b2bd547918c0)

#### [v0.2.1](https://github.com/CookPete/auto-changelog/compare/v0.2.0...v0.2.1)

> 2 January 2016

- Replace toLocaleString usage with months array [`0008264`](https://github.com/CookPete/auto-changelog/commit/0008264bcabddf8d2b6b19fde7aa41b0de7a5b77)

#### [v0.2.0](https://github.com/CookPete/auto-changelog/compare/v0.1.1...v0.2.0)

> 2 January 2016

- Add support for specifying templates [`369b51e`](https://github.com/CookPete/auto-changelog/commit/369b51e9ff05bccba19cd09d9d519bca579bf972)
- Add FAQ to readme [`9351ad0`](https://github.com/CookPete/auto-changelog/commit/9351ad0b5f6e7f59e1b51b1c7ea1a3e7720dfbbc)
- Rearrange usage docs [`c6bfb0b`](https://github.com/CookPete/auto-changelog/commit/c6bfb0be0b429ce7f9697eb1097ec3e2288aff74)

#### [v0.1.1](https://github.com/CookPete/auto-changelog/compare/v0.1.0...v0.1.1)

> 31 December 2015

- Explicitly render links for PRs and issues [`0a384cd`](https://github.com/CookPete/auto-changelog/commit/0a384cdeb3e9c3641fc3f655b0d9aeff58f8ebd3)
- Fix --package bug [`7f12f81`](https://github.com/CookPete/auto-changelog/commit/7f12f81f06441af4c74508ccc673e7052dec8d18)

#### [v0.1.0](https://github.com/CookPete/auto-changelog/compare/v0.0.1...v0.1.0)

> 31 December 2015

- Add option for specifying output file [`#1`](https://github.com/CookPete/auto-changelog/issues/1)
- Add support for --package [`772fbb9`](https://github.com/CookPete/auto-changelog/commit/772fbb988f41d893bccd88417a2b5992543bc936)
- Update badges [`d17791f`](https://github.com/CookPete/auto-changelog/commit/d17791f478b7fc4a48877b5c79a1ce857223553a)
- Remove todo list from readme [`4446226`](https://github.com/CookPete/auto-changelog/commit/4446226048642ad19a7bfbc1c2f8040a6d15cbc3)

#### v0.0.1

> 31 December 2015

- First commit [`436b409`](https://github.com/CookPete/auto-changelog/commit/436b409bb6b3f853d14e2eda6ca1d87f78d00a14)

**Comment by vania-pooh** [comment]
@conradkirschner are you seeing this under releases page?
<img width="793" alt="Screen Shot 2020-08-28 at 07 19 40" src="https://user-images.githubusercontent.com/829320/91520822-e9331e00-e8fe-11ea-8124-7df8642c9375.png">

**Comment by Expoverse** [comment]
From the screenshot changelogs will be much better and less clutter. Not in my brightest moment right now, on a trip, but can we regenerate older release changelogs to follow this format?
