### ISSUE TITLE
Can't change browser window size

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-images#7]
Setting screen resolution work but can't maximize window.

**Comment by vania-pooh** [comment]
Works with `window().setSize().`.

**Comment by nebehr** [comment]
Should window maximization at all work in current Selenoid images, or only ```window().setSize()``` is supported? I see that ```window().maximize()``` fails in Chrome ("failed to change window state to maximized, current state is normal") but works in FF, and I believe the same issue is or was observed in the "official" docker-selenium images, quite possibly due to lack of window manager in the containers. So I am not sure if current behaviour is a bug or works as designed.

**Comment by vania-pooh** [comment]
Not sure too but also not sure whether we really need installing windows manager for that. :)
