### ISSUE TITLE
Window manager missing in Chrome 68 and above

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/selenoid-images#76]
I have just realized that the Selenoid Docker image for Chrome 67 was the last version with the windows manager (Fluxbox) working properly:

![screenshot from 2018-12-18 14-18-53](https://user-images.githubusercontent.com/5413013/50156760-e382d980-02cf-11e9-95f4-487631595272.png)

As proof of that, as can be seen in the picture before, the custom Selenoid wallpaper appears.

In Chrome 68 and above the windows manager seems to be missing:

![screenshot from 2018-12-18 14-19-53](https://user-images.githubusercontent.com/5413013/50156812-01e8d500-02d0-11e9-89cb-ef32a13dc3c5.png)

Is this related to #46?

**Comment by vania-pooh** [comment]
@bonigarcia it is there but we found that sometimes browsers are started after window manager and `maximize()` stops working. To enable window manager as is - just add `ENABLE_WINDOW_MANAGER` environment variable in `browsers.json`. This issue is going to be fixed in the updated images (https://github.com/aerokube/selenoid-images/issues/54).

**Comment by bonigarcia** [comment]
Thanks @vania-pooh.
